export const PERMISSIONS = {
  DASHBOARD_VIEW: "dashboard.overview.view",
  ASSET_VIEW: "asset.register.view",
  ASSET_CREATE: "asset.register.create",
  ASSET_EDIT: "asset.register.edit",
  ASSET_DELETE: "asset.register.delete",
  ASSET_ASSIGN: "asset.assignments.assign",
  QR_GENERATE: "asset.register.export",
  QR_SCAN: "asset.register.view",
  REQUEST_VIEW: "request.procurement.view",
  REQUEST_CREATE: "request.procurement.create",
  REQUEST_APPROVE: "request.procurement.approve",
  REQUEST_REJECT: "request.procurement.reject",
  INVENTORY_VIEW: "inventory.stock.view",
  INVENTORY_MANAGE: "inventory.stock.edit",
  MAINTENANCE_VIEW: "maintenance.logs.view",
  MAINTENANCE_MANAGE: "maintenance.logs.edit",
  WARRANTY_VIEW: "warranty.tracker.view",
  WARRANTY_MANAGE: "warranty.tracker.edit",
  EMPLOYEE_PORTAL: "employee.portal.view",
  USER_MANAGE: "employee.users.edit",
  OFFICE_VIEW: "office.offices.view",
  OFFICE_MANAGE: "office.offices.edit",
  REPORT_VIEW: "report.reports.view",
  REPORT_EXPORT: "report.reports.export",
  AUDIT_VIEW: "asset.register.view",
  AUDIT_MANAGE: "asset.register.edit",
  SYSTEM_SETTINGS: "settings.preferences.view",
  PROCUREMENT_MANAGE: "request.procurement.edit",
  WORK_ORDERS_MANAGE: "maintenance.logs.edit",
};

export const DEFAULT_ROLE_PERMISSIONS = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  COMPANY_ADMIN: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ASSET_VIEW,
    PERMISSIONS.ASSET_CREATE,
    PERMISSIONS.ASSET_EDIT,
    PERMISSIONS.ASSET_DELETE,
    PERMISSIONS.ASSET_ASSIGN,
    PERMISSIONS.QR_GENERATE,
    PERMISSIONS.QR_SCAN,
    PERMISSIONS.REQUEST_VIEW,
    PERMISSIONS.REQUEST_APPROVE,
    PERMISSIONS.REQUEST_REJECT,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.MAINTENANCE_VIEW,
    PERMISSIONS.MAINTENANCE_MANAGE,
    PERMISSIONS.WARRANTY_VIEW,
    PERMISSIONS.WARRANTY_MANAGE,
    PERMISSIONS.EMPLOYEE_PORTAL,
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.OFFICE_VIEW,
    PERMISSIONS.OFFICE_MANAGE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.PROCUREMENT_MANAGE,
    PERMISSIONS.WORK_ORDERS_MANAGE,
  ],
  BRANCH_ADMIN: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ASSET_VIEW,
    PERMISSIONS.ASSET_CREATE,
    PERMISSIONS.ASSET_EDIT,
    PERMISSIONS.ASSET_DELETE,
    PERMISSIONS.ASSET_ASSIGN,
    PERMISSIONS.QR_GENERATE,
    PERMISSIONS.QR_SCAN,
    PERMISSIONS.REQUEST_VIEW,
    PERMISSIONS.REQUEST_APPROVE,
    PERMISSIONS.REQUEST_REJECT,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.MAINTENANCE_VIEW,
    PERMISSIONS.MAINTENANCE_MANAGE,
    PERMISSIONS.WARRANTY_VIEW,
    PERMISSIONS.WARRANTY_MANAGE,
    PERMISSIONS.EMPLOYEE_PORTAL,
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.OFFICE_VIEW,
    PERMISSIONS.OFFICE_MANAGE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.PROCUREMENT_MANAGE,
    PERMISSIONS.WORK_ORDERS_MANAGE,
  ],
  ADMIN: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ASSET_VIEW,
    PERMISSIONS.ASSET_CREATE,
    PERMISSIONS.ASSET_EDIT,
    PERMISSIONS.ASSET_DELETE,
    PERMISSIONS.ASSET_ASSIGN,
    PERMISSIONS.QR_GENERATE,
    PERMISSIONS.QR_SCAN,
    PERMISSIONS.REQUEST_VIEW,
    PERMISSIONS.REQUEST_APPROVE,
    PERMISSIONS.REQUEST_REJECT,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.MAINTENANCE_VIEW,
    PERMISSIONS.MAINTENANCE_MANAGE,
    PERMISSIONS.WARRANTY_VIEW,
    PERMISSIONS.WARRANTY_MANAGE,
    PERMISSIONS.EMPLOYEE_PORTAL,
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.OFFICE_VIEW,
    PERMISSIONS.OFFICE_MANAGE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.PROCUREMENT_MANAGE,
    PERMISSIONS.WORK_ORDERS_MANAGE,
  ],
  IT_STAFF: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ASSET_VIEW,
    PERMISSIONS.ASSET_CREATE,
    PERMISSIONS.ASSET_EDIT,
    PERMISSIONS.ASSET_ASSIGN,
    PERMISSIONS.QR_GENERATE,
    PERMISSIONS.QR_SCAN,
    PERMISSIONS.REQUEST_VIEW,
    PERMISSIONS.REQUEST_CREATE,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.MAINTENANCE_VIEW,
    PERMISSIONS.MAINTENANCE_MANAGE,
    PERMISSIONS.WARRANTY_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.PROCUREMENT_MANAGE,
    PERMISSIONS.WORK_ORDERS_MANAGE,
  ],
  MANAGER: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ASSET_VIEW,
    PERMISSIONS.REQUEST_VIEW,
    PERMISSIONS.REQUEST_APPROVE,
    PERMISSIONS.REQUEST_REJECT,
    PERMISSIONS.REPORT_VIEW,
  ],
  EMPLOYEE: [
    PERMISSIONS.EMPLOYEE_PORTAL,
    PERMISSIONS.ASSET_VIEW,
    PERMISSIONS.REQUEST_CREATE,
    PERMISSIONS.REQUEST_VIEW,
    PERMISSIONS.WARRANTY_VIEW,
    PERMISSIONS.QR_SCAN,
  ],
  AUDITOR: [
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.ASSET_VIEW,
  ],
};

export const DEFAULT_ROLE_SIDEBAR = {
  SUPER_ADMIN: [
    "Dashboard",
    "Assets",
    "Masters",
    "QR Console",
    "Requests",
    "Approvals",
    "Procurements",
    "Inventory",
    "Work Orders",
    "Employee Portal",
    "Assignments",
    "Maintenance",
    "Warranty",
    "Offices",
    "Audit Session",
    "Reports",
    "Users & Access",
    "Setup",
    "Users",
    "Vendors",
    "Products",
    "Preferences",
    "My Assets",
  ],
  COMPANY_ADMIN: [
    "Dashboard",
    "Assets",
    "Masters",
    "QR Console",
    "Requests",
    "Approvals",
    "Procurements",
    "Inventory",
    "Work Orders",
    "Employee Portal",
    "Assignments",
    "Maintenance",
    "Warranty",
    "Offices",
    "Audit Session",
    "Reports",
    "Users & Access",
    "Setup",
    "Users",
    "Vendors",
    "Products",
    "Preferences",
    "My Assets",
  ],
  BRANCH_ADMIN: [
    "Dashboard",
    "Assets",
    "Masters",
    "QR Console",
    "Requests",
    "Approvals",
    "Procurements",
    "Inventory",
    "Work Orders",
    "Employee Portal",
    "Assignments",
    "Maintenance",
    "Warranty",
    "Offices",
    "Audit Session",
    "Reports",
    "Users & Access",
    "Setup",
    "Users",
    "Vendors",
    "Products",
    "Preferences",
    "My Assets",
  ],
  ADMIN: [
    "Dashboard",
    "Assets",
    "Masters",
    "QR Console",
    "Requests",
    "Approvals",
    "Procurements",
    "Inventory",
    "Work Orders",
    "Employee Portal",
    "Assignments",
    "Maintenance",
    "Warranty",
    "Offices",
    "Audit Session",
    "Reports",
    "Users & Access",
    "Setup",
    "Users",
    "Vendors",
    "Products",
    "Preferences",
    "My Assets",
  ],
  IT_STAFF: [
    "Dashboard",
    "Assets",
    "QR Console",
    "Requests",
    "Procurements",
    "Inventory",
    "Work Orders",
    "Assignments",
    "Maintenance",
    "Warranty",
    "Reports",
    "Masters",
    "Setup",
    "Vendors",
    "Products",
    "My Assets",
  ],
  MANAGER: ["Dashboard", "Assets", "Requests", "Approvals", "Reports", "Setup", "Products", "My Assets"],
  EMPLOYEE: ["Employee Portal", "Requests", "Warranty", "QR Console", "My Assets"],
  AUDITOR: ["Audit Session", "Reports", "Assets", "Setup", "Products", "My Assets"],
};
