export const PERMISSIONS = {
  DASHBOARD_VIEW: "dashboard.view",
  ASSET_VIEW: "assets.view",
  ASSET_CREATE: "assets.create",
  ASSET_EDIT: "assets.edit",
  ASSET_DELETE: "assets.delete",
  ASSET_ASSIGN: "assignments.manage",
  QR_GENERATE: "qrconsole.generate",
  QR_SCAN: "qrconsole.scan",
  REQUEST_VIEW: "requests.view",
  REQUEST_CREATE: "requests.create",
  REQUEST_APPROVE: "approvals.approve",
  REQUEST_REJECT: "approvals.reject",
  INVENTORY_VIEW: "inventory.view",
  INVENTORY_MANAGE: "inventory.manage",
  MAINTENANCE_VIEW: "maintenance.view",
  MAINTENANCE_MANAGE: "maintenance.manage",
  WARRANTY_VIEW: "warranty.view",
  WARRANTY_MANAGE: "warranty.manage",
  EMPLOYEE_PORTAL: "employeeportal.view",
  USER_MANAGE: "usersaccess.manage",
  OFFICE_VIEW: "offices.view",
  OFFICE_MANAGE: "offices.manage",
  REPORT_VIEW: "reports.view",
  REPORT_EXPORT: "reports.export",
  AUDIT_VIEW: "auditsession.view",
  AUDIT_MANAGE: "auditsession.manage",
  SYSTEM_SETTINGS: "setup.manage",
  PROCUREMENT_MANAGE: "procurements.manage",
  WORK_ORDERS_MANAGE: "workorders.manage",
  TRACKING_VIEW: "tracking.view",
  MY_ASSETS_VIEW: "myassets.view",
};

export const DEFAULT_ROLE_PERMISSIONS = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  COMPANY_ADMIN: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ASSET_VIEW,
    PERMISSIONS.ASSET_CREATE,
    PERMISSIONS.ASSET_EDIT,
    PERMISSIONS.ASSET_DELETE,
    PERMISSIONS.ASSET_ASSIGN,
    PERMISSIONS.QR_GENERATE,
    PERMISSIONS.QR_SCAN,
    PERMISSIONS.REQUEST_VIEW,
    PERMISSIONS.REQUEST_APPROVE,
    PERMISSIONS.REQUEST_REJECT,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.MAINTENANCE_VIEW,
    PERMISSIONS.MAINTENANCE_MANAGE,
    PERMISSIONS.WARRANTY_VIEW,
    PERMISSIONS.WARRANTY_MANAGE,
    PERMISSIONS.EMPLOYEE_PORTAL,
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.OFFICE_VIEW,
    PERMISSIONS.OFFICE_MANAGE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.AUDIT_MANAGE,
    PERMISSIONS.SYSTEM_SETTINGS,
    PERMISSIONS.PROCUREMENT_MANAGE,
    PERMISSIONS.WORK_ORDERS_MANAGE,
    PERMISSIONS.TRACKING_VIEW,
    PERMISSIONS.MY_ASSETS_VIEW,
  ],
  BRANCH_ADMIN: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ASSET_VIEW,
    PERMISSIONS.ASSET_CREATE,
    PERMISSIONS.ASSET_EDIT,
    PERMISSIONS.ASSET_DELETE,
    PERMISSIONS.ASSET_ASSIGN,
    PERMISSIONS.QR_GENERATE,
    PERMISSIONS.QR_SCAN,
    PERMISSIONS.REQUEST_VIEW,
    PERMISSIONS.REQUEST_APPROVE,
    PERMISSIONS.REQUEST_REJECT,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.MAINTENANCE_VIEW,
    PERMISSIONS.MAINTENANCE_MANAGE,
    PERMISSIONS.WARRANTY_VIEW,
    PERMISSIONS.WARRANTY_MANAGE,
    PERMISSIONS.EMPLOYEE_PORTAL,
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.OFFICE_VIEW,
    PERMISSIONS.OFFICE_MANAGE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.AUDIT_MANAGE,
    PERMISSIONS.SYSTEM_SETTINGS,
    PERMISSIONS.PROCUREMENT_MANAGE,
    PERMISSIONS.WORK_ORDERS_MANAGE,
    PERMISSIONS.TRACKING_VIEW,
    PERMISSIONS.MY_ASSETS_VIEW,
  ],
  ADMIN: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ASSET_VIEW,
    PERMISSIONS.ASSET_CREATE,
    PERMISSIONS.ASSET_EDIT,
    PERMISSIONS.ASSET_DELETE,
    PERMISSIONS.ASSET_ASSIGN,
    PERMISSIONS.QR_GENERATE,
    PERMISSIONS.QR_SCAN,
    PERMISSIONS.REQUEST_VIEW,
    PERMISSIONS.REQUEST_APPROVE,
    PERMISSIONS.REQUEST_REJECT,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.MAINTENANCE_VIEW,
    PERMISSIONS.MAINTENANCE_MANAGE,
    PERMISSIONS.WARRANTY_VIEW,
    PERMISSIONS.WARRANTY_MANAGE,
    PERMISSIONS.EMPLOYEE_PORTAL,
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.OFFICE_VIEW,
    PERMISSIONS.OFFICE_MANAGE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.AUDIT_MANAGE,
    PERMISSIONS.SYSTEM_SETTINGS,
    PERMISSIONS.PROCUREMENT_MANAGE,
    PERMISSIONS.WORK_ORDERS_MANAGE,
    PERMISSIONS.TRACKING_VIEW,
    PERMISSIONS.MY_ASSETS_VIEW,
  ],
  IT_STAFF: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ASSET_VIEW,
    PERMISSIONS.ASSET_CREATE,
    PERMISSIONS.ASSET_EDIT,
    PERMISSIONS.ASSET_DELETE,
    PERMISSIONS.ASSET_ASSIGN,
    PERMISSIONS.QR_GENERATE,
    PERMISSIONS.QR_SCAN,
    PERMISSIONS.TRACKING_VIEW,
    PERMISSIONS.MAINTENANCE_VIEW,
    PERMISSIONS.MAINTENANCE_MANAGE,
    PERMISSIONS.WARRANTY_VIEW,
    PERMISSIONS.WARRANTY_MANAGE,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.REQUEST_VIEW,
    PERMISSIONS.REQUEST_CREATE,
    PERMISSIONS.MY_ASSETS_VIEW,
    PERMISSIONS.WORK_ORDERS_MANAGE,
    PERMISSIONS.EMPLOYEE_PORTAL,
  ],
  MANAGER: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ASSET_VIEW,
    PERMISSIONS.ASSET_CREATE,
    PERMISSIONS.ASSET_EDIT,
    PERMISSIONS.ASSET_DELETE,
    PERMISSIONS.REQUEST_VIEW,
    PERMISSIONS.REQUEST_CREATE,
    PERMISSIONS.REQUEST_APPROVE,
    PERMISSIONS.REQUEST_REJECT,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.ASSET_ASSIGN,
    PERMISSIONS.MY_ASSETS_VIEW,
    PERMISSIONS.EMPLOYEE_PORTAL,
  ],
  EMPLOYEE: [
    PERMISSIONS.MY_ASSETS_VIEW,
    PERMISSIONS.REQUEST_CREATE,
    PERMISSIONS.REQUEST_VIEW,
    PERMISSIONS.QR_SCAN,
    PERMISSIONS.QR_GENERATE,
    PERMISSIONS.EMPLOYEE_PORTAL,
  ],
  AUDITOR: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ASSET_VIEW,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.AUDIT_MANAGE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.MY_ASSETS_VIEW,
    PERMISSIONS.EMPLOYEE_PORTAL,
  ],
};

export const DEFAULT_ROLE_SIDEBAR = {
  SUPER_ADMIN: [
    "Dashboard",
    "Assets",
    "Masters",
    "QR Console",
    "Requests",
    "Approvals",
    "Procurements",
    "Inventory",
    "Work Orders",
    "Employee Portal",
    "Assignments",
    "Maintenance",
    "Warranty",
    "Offices",
    "Audit Session",
    "Reports",
    "Users & Access",
    "Setup",
    "Users",
    "Vendors",
    "Products",
    "Preferences",
    "My Assets",
  ],
  COMPANY_ADMIN: [
    "Dashboard",
    "Assets",
    "Masters",
    "QR Console",
    "Requests",
    "Approvals",
    "Procurements",
    "Inventory",
    "Work Orders",
    "Employee Portal",
    "Assignments",
    "Maintenance",
    "Warranty",
    "Offices",
    "Audit Session",
    "Reports",
    "Users & Access",
    "Setup",
    "Users",
    "Vendors",
    "Products",
    "Preferences",
    "My Assets",
  ],
  BRANCH_ADMIN: [
    "Dashboard",
    "Assets",
    "Masters",
    "QR Console",
    "Requests",
    "Approvals",
    "Procurements",
    "Inventory",
    "Work Orders",
    "Employee Portal",
    "Assignments",
    "Maintenance",
    "Warranty",
    "Offices",
    "Audit Session",
    "Reports",
    "Users & Access",
    "Setup",
    "Users",
    "Vendors",
    "Products",
    "Preferences",
    "My Assets",
  ],
  ADMIN: [
    "Dashboard",
    "Assets",
    "Masters",
    "QR Console",
    "Requests",
    "Approvals",
    "Procurements",
    "Inventory",
    "Work Orders",
    "Employee Portal",
    "Assignments",
    "Maintenance",
    "Warranty",
    "Offices",
    "Audit Session",
    "Reports",
    "Users & Access",
    "Setup",
    "Users",
    "Vendors",
    "Products",
    "Preferences",
    "My Assets",
  ],
  IT_STAFF: [
    "Dashboard",
    "Assets",
    "QR Console",
    "Tracking",
    "Assignments",
    "Maintenance",
    "Warranty",
    "Work Orders",
    "Inventory",
    "Requests",
    "My Assets",
  ],
  MANAGER: [
    "Dashboard",
    "Assets",
    "Requests",
    "Approvals",
    "Reports",
    "My Assets",
    "Employee Portal",
    "Assignments",
  ],
  EMPLOYEE: [
    "My Assets",
    "Requests",
    "Employee Portal",
    "QR Console",
  ],
  AUDITOR: [
    "Dashboard",
    "Assets",
    "Audit Session",
    "Reports",
    "My Assets",
  ],
};
